auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: weiborecom.com
url: http://weiborecom.github.io
feed: /atom.xml
author_info: <a href="http://weiborecom.github.io/">WeiboRecom</a>
